create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null,
  password text not null,
  role text not null check (role in ('admin', 'driver')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists users_username_lower_idx on users (lower(username));

create table if not exists trucks (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#cccccc',
  created_at timestamptz not null default now()
);

create table if not exists entries (
  id uuid primary key default gen_random_uuid(),
  truck text not null,
  "user" text not null,
  driver text not null,
  date text not null,
  odometer numeric not null check (odometer >= 0),
  fuel numeric not null default 0 check (fuel >= 0),
  created_at timestamptz not null default now()
);

create index if not exists entries_truck_created_at_idx on entries (truck, created_at desc);

create table if not exists sessions (
  id bigint generated always as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists sessions_expires_at_idx on sessions (expires_at);

comment on column users.password is 'bcrypt password hash; never return this column to browser clients';
